import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { ReactNode } from 'react';
import Navbar from '@/components/nav/Navbar';
import getCurrentUser from '@/app/actions/getCurrentUser';
import Script from 'next/script';
import ToastProvider from '@/components/ToastProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar currentUser={currentUser} />
        <ToastProvider />
        {children}
        <Script src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=8d895cc249f60bcc302467ed13331611&autoload=false&libraries=services,clusterer&autoload=false" />
      </body>
    </html>
  );
}
